# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Amass < Formula
  desc "In-depth Attack Surface Mapping and Asset Discovery"
  homepage "https://owasp.org/www-project-amass/"
  version "3.23.76"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/The-Inceptions-Test/amass/releases/download/v3.23.76/amass_Darwin_amd64.zip"
      sha256 "28c9bbb35c05f7ec4979201bfac3216973f8818fb88583b23b0afcf6fae482fb"

      def install
        bin.install "amass"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/The-Inceptions-Test/amass/releases/download/v3.23.76/amass_Darwin_arm64.zip"
      sha256 "dcf76ce75943cc31310e527610e9f32b32aa1a4bef79914052687976953db31b"

      def install
        bin.install "amass"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/The-Inceptions-Test/amass/releases/download/v3.23.76/amass_Linux_arm64.zip"
      sha256 "3d37ec9e14b2dc1fd408e06cc0eecd1da03aa263542303b77e64eb56acb9ef5d"

      def install
        bin.install "amass"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/The-Inceptions-Test/amass/releases/download/v3.23.76/amass_Linux_amd64.zip"
      sha256 "81116012e871dd77ad233cd34c12d3dd5a1920253b5b1e1a6fd5ec8f29808f82"

      def install
        bin.install "amass"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/The-Inceptions-Test/amass/releases/download/v3.23.76/amass_Linux_arm.zip"
      sha256 "0cd2edc2bdcf6ca3eee34fb11206f91ae1325737a1711bb56ed1dabc473a5631"

      def install
        bin.install "amass"
      end
    end
  end

  test do
    system "#{bin}/amass --version"
  end
end
